Require numpy==1.16.4.
The most recent version of numpy (1.19.1) caused an error:

IndexError: arrays used as indices must be of integer (or boolean) type

See issue for reference. Looks like this is an empirical finding.
https://github.com/tensorflow/tensorflow/issues/31249